trigger:
  - main

resources:
  - repo: self

variables:
  imageName: "ghcr.io/lalatinahub/latinaapi:main"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: BuildAndPush
        displayName: Build and Push Docker Image
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: docker login ghcr.io -u dickymuliafiqri -p $(DOCKER_PASS)
            displayName: Login to docker container
          - bash: docker build -t $(imageName) .
            displayName: Build docker image
          - bash: docker push $(imageName)
            displayName: Push docker image to container
      - job: RestartWebApp
        dependsOn: BuildAndPush
        displayName: Restart WebApp
        steps:
          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: 'Azure for Students Starter(da8c2850-a4f7-4cda-95d7-1e6ebd821a16)'
              Action: 'Restart Azure App Service'
              WebAppName: 'fool'
