# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build Docker Image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'ghcr.io/lalatinahub/latinaapi:main'
  - job: Push
    displayName: Push Docker Image
    pool:
      vmImage: ubuntu-latest
    steps:
      - bash: docker login ghcr.io -u dickymuliafiqri -p $(DOCKER_PASS)
        displayName: Login to docker container
      - bash: docker push ghcr.io/lalatinahub/latinaapi:main
        displayName: Push docker image to container
